TITLE Eco
.MODEL SMALL
.CODE
MAIN PROC
    ;EXIBE O CARACTER '?' NA TELA
    MOV AH, 2
    MOV DL, "?"
    INT 21h

    ;LE UM CARACTER DO TECLADO E SALVA O CARACTER LIDO EM AL
    MOV AH,1        
    INT 21h
    
    ;COPIA O CARACTER LIDO PARA BL
    MOV BL, AL

    ;EXIBE O CARACTER LINE FEED (MOVE O CURSOR PARA A LINHA SEGUINTE)
    MOV AH,2
    MOV DL,10 ; O CÓDIGO ASC DO CARACTER LINE FEED É 10 (0Ah)
    SUB BL, 32
    INT 21h

    ;EXIBE O CARACTER CARRIAGE RETURN (MOVE O CURSOR PARA O CANTO ESQUERDO DA TELA)
    MOV AH,2
    MOV DL,13 ;O CÓDIGO ASC DO CARACTER CARRIAGE RETURN É 13 (0DH)
    INT 21h

    ;EXIBE O CARACTER LIDO
    MOV AH, 2
    MOV DL, BL
    INT 21h
    
    ;FINALIZA O PROGRAMA
    MOV AH, 4Ch
    INT 21h
    MAIN ENDP
END MAIN